# Generated by Django 4.2.1 on 2024-08-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='author',
        ),
        migrations.RemoveField(
            model_name='about',
            name='excerpt',
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
